name: Rust CI (Pull Request check)

on:
    pull_request:
        paths:
            - 'src-tauri/**'
            - 'Cargo.toml'
            - 'Cargo.lock'

jobs:
    check:
        name: cargo check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              run: rustup default stable
            - name: cargo check
              working-directory: ./src-tauri
              run: cargo check --lib

    clippy:
        name: cargo clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              run: rustup default stable
            - name: cargo clippy
              working-directory: ./src-tauri
              run: cargo clippy --lib -- -D warnings

    test:
        name: cargo test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              run: rustup default stable
            - name: cargo test
              working-directory: ./src-tauri
              run: cargo test --lib
